### ISSUE TITLE
Implement a React Component that provides access to the new Zendro extended search

### ISSUE THREAD

**Issue by asishallab** [Zendro-dev/graphiql-auth#3]
### Introduction

Zendro has extended or meta-search support in which one or many GraphQL queries can be sent and their joint results parsed and transformed by either an `jq` or an `jsonPath` expression. The specification can be seen in the [corresponding integration tests (line 318 following)](https://github.com/ScienceDb/graphql-server-model-codegen/blob/master/test/mocha_integration_test.js) and in the [respective whitepaper](https://docs.google.com/document/d/121ACqaIn7qnfNl4sKruPNTT63r4jwF3o1I21RqZRzA4/edit?usp=sharing).

### Extend the GraphiQL interface to support meta-searches

After successful sign-in the user is shown an extended interface. Introduce tabs into the GraphiQL interface. In the first "GraphiQL" named tab the interface is as it currently is, in the second "Meta-Search" interface the user is provided access to the meta-search functionality implemented in the backend GraphQL server. See [this sketch](https://docs.google.com/drawings/d/1DHdq46msXqpc6hhF9do9gTgjEXNGCqUXG9_SnHFH1t8/edit?usp=sharing) of how this tab roughly should look like.

### General design

Use Google's material design or Facebook's GraphiQL look and feel for the new component. Apply your experience in the development of the Zendro single-page-application to give the new interface a professional look and feel. 

### Behavior of the interface

In the [general sketch](https://docs.google.com/drawings/d/1DHdq46msXqpc6hhF9do9gTgjEXNGCqUXG9_SnHFH1t8/edit?usp=sharing) you see three input fields into which the user can paste GraphQL queries copied from the GraphiQL interface. In the beginning the user sees _only_ a single input field. If the little "plus" icon is clicked another input field is opened. All queries in these input fields are gathered and sent to the GraphQL server's meta-search should the "execute" button be pressed. The selection menu enables to send either a `jq` or a `jsonPath` expression. In the JSON-Result pane the result as sent by the GraphQL server's meta-search is displayed. Should an error have been generated the error is shown (see below).

### Error display

Two options can be chosen from. Either implement error messages with a snack-bar as it has been done in the Single Page Application, or display them as they are in the GraphiQL interface. In the latter the server's response simply has an error property. See how the meta-search is implemented and choose appropriately.

**Comment by framirez07** [comment]
The following points were discussed and accepted:
- Functionality to add multiple queries is already supported by the graphiql component, so we can omit to add new components to add multiple queries.
- Add a new menu-button in the current graphiql's toolbar, where the user can choose some filter option: JQ or JsonPath, or none.
- When the user chooses some filter option (not "none"), an input component will be displayed just below the toolbar, scrolling the main query panel down, so that the user can add the filter on the input component.
